import React, { useEffect, useState } from 'react';
import { 
  FileCode, 
  Copy, 
  Check, 
  Terminal, 
  Sparkles, 
  ExternalLink, 
  Palette, 
  Type, 
  Ruler, 
  Box, 
  FileCheck,
  RefreshCw,
  Info,
  Download
} from 'lucide-react';
import { GeneratedDocument } from '../types';

interface LiveOutputProps {
  documentData: GeneratedDocument;
  isGenerating: boolean;
}

const LOADING_MESSAGES = [
  'Your DESIGN.md file is almost ready',
  "We're almost done cooking",
  'Turning extracted tokens into a clean spec',
  'Finalizing the Doc Spec and snippets',
];

export default function LiveOutput({ documentData, isGenerating }: LiveOutputProps) {
  const [activeTab, setActiveTab] = useState<'DOCUMENT' | 'MARKDOWN' | 'CODE_EXPORT'>('DOCUMENT');
  const [copiedColor, setCopiedColor] = useState<string | null>(null);
  const [copiedCodeIdx, setCopiedCodeIdx] = useState<number | null>(null);
  const [copiedMd, setCopiedMd] = useState(false);
  const [interactiveBtnState, setInteractiveBtnState] = useState<'Default' | 'Hover' | 'Pressed'>('Default');
  const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);

  useEffect(() => {
    if (!isGenerating) {
      setLoadingMessageIndex(0);
      return;
    }

    const interval = window.setInterval(() => {
      setLoadingMessageIndex((current) => (current + 1) % LOADING_MESSAGES.length);
    }, 3200);

    return () => window.clearInterval(interval);
  }, [isGenerating]);

  // Interactive copying
  const copyColorToClipboard = (hex: string) => {
    navigator.clipboard.writeText(hex);
    setCopiedColor(hex);
    setTimeout(() => setCopiedColor(null), 1500);
  };

  const copyCodeToClipboard = (code: string, idx: number) => {
    navigator.clipboard.writeText(code);
    setCopiedCodeIdx(idx);
    setTimeout(() => setCopiedCodeIdx(null), 1500);
  };

  const copyMarkdownToClipboard = () => {
    navigator.clipboard.writeText(documentData.markdown);
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const downloadMarkdown = () => {
    const blob = new Blob([documentData.markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const safeTitle = documentData.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'design';

    link.href = url;
    link.download = `${safeTitle}.design.md`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  const cssVariableSnippet = `:root {\n${documentData.colors
    .map((color) => `  --color-${slugify(color.name)}: ${color.hex};`)
    .join('\n')}\n}`;
  const tailwindColorSnippet = `colors: {\n${documentData.colors
    .map((color) => `  "${slugify(color.name)}": "${color.hex}",`)
    .join('\n')}\n}`;
  const implementationSnippets = documentData.components.filter((component) => component.codeSnippet.trim().length > 0);

  return (
    <section id="preview" className="border-b border-border-match bg-bg-black py-16 sm:py-20 relative custom-scanlines">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-12">
          <span className="font-mono text-xs text-accent-pink uppercase tracking-widest block mb-1">Generated Output Sandbox</span>
          <h2 className="font-pixel-square text-3xl sm:text-4xl text-text-white mb-3 uppercase tracking-tight">
            Live DESIGN.md Output
          </h2>
          <p className="font-geist text-sm text-muted-text">
            Explore the production-ready documentation generated by the Claude model from your source assets below.
          </p>
        </div>

        {/* Console Hub / Layout Panel */}
        <div className="rounded-lg border border-border-match bg-surf-1 overflow-hidden shadow-2xl text-left">
          
          {/* Header controllers */}
          <div className="bg-surf-2 border-b border-border-match px-6 py-4 flex flex-col sm:flex-row justify-between items-center gap-4">
            
            <div className="flex items-center gap-2.5">
              <div className="h-2.5 w-2.5 rounded-full bg-success-green animate-pulse" />
              <div>
                <span className="text-xs font-mono font-bold text-text-white uppercase tracking-wider block">
                  {documentData.title} Spec Sheet
                </span>
                <span className="text-xs font-mono text-text-3">
                  Parsed At: {documentData.createdAt} • Confidence: {(documentData.confidence * 100).toFixed(0)}%
                </span>
              </div>
            </div>

            {/* Output View Controller */}
            <div className={`flex bg-bg-black/80 rounded border border-border-match p-0.5 w-full sm:w-auto ${isGenerating ? 'opacity-50' : ''}`}>
              <button
                onClick={() => setActiveTab('DOCUMENT')}
                disabled={isGenerating}
                className={`flex-1 sm:flex-none px-4 py-1.5 rounded text-xs font-mono transition-all cursor-pointer ${activeTab === 'DOCUMENT' ? 'bg-accent-pink text-black font-semibold' : 'text-text-3 hover:text-text-1'}`}
              >
                <span><span className="hidden sm:inline">[01] </span>Doc Spec</span>
              </button>
              <button
                onClick={() => setActiveTab('MARKDOWN')}
                disabled={isGenerating}
                className={`flex-1 sm:flex-none px-4 py-1.5 rounded text-xs font-mono transition-all cursor-pointer ${activeTab === 'MARKDOWN' ? 'bg-accent-pink text-black font-semibold' : 'text-text-3 hover:text-text-1'}`}
              >
                <span><span className="hidden sm:inline">[02] </span>DESIGN.md</span>
              </button>
              <button
                onClick={() => setActiveTab('CODE_EXPORT')}
                disabled={isGenerating}
                className={`flex-1 sm:flex-none px-4 py-1.5 rounded text-xs font-mono transition-all cursor-pointer ${activeTab === 'CODE_EXPORT' ? 'bg-accent-pink text-black font-semibold' : 'text-text-3 hover:text-text-1'}`}
              >
                <span><span className="hidden sm:inline">[03] </span>Snippets</span>
              </button>
            </div>

          </div>

          <div className="p-6 bg-bg-black/50">
            {isGenerating && (
              <div className="animate-fade-in py-2">
                <div className="relative mx-auto aspect-video w-full max-w-3xl overflow-hidden bg-black">
                  <video
                    className="h-full w-full scale-105 object-cover opacity-65 blur-[2px]"
                    src="/placeholder-video.mp4"
                    autoPlay
                    loop
                    muted
                    playsInline
                    aria-label="DESIGN.md generation placeholder animation"
                  />
                  <div className="absolute inset-0 bg-black/55 custom-scanlines" />
                  <div className="absolute inset-0 flex items-center justify-center px-5 text-center">
                    <div className="max-w-xl">
                      <span className="font-mono text-xs uppercase tracking-widest text-accent-pink">
                        Generating DESIGN.md
                      </span>
                      <p className="mt-4 font-geist text-2xl font-bold uppercase leading-tight text-text-white sm:text-3xl">
                        {LOADING_MESSAGES[loadingMessageIndex]}
                        <span className="ml-1 inline-flex w-8 justify-start text-accent-pink" aria-hidden="true">
                          <span className="animate-pulse">.</span>
                          <span className="animate-pulse [animation-delay:160ms]">.</span>
                          <span className="animate-pulse [animation-delay:320ms]">.</span>
                        </span>
                      </p>
                      <p className="mx-auto mt-3 max-w-md text-xs leading-relaxed text-[#A0A0A0]">
                        The final DESIGN.md download, Doc Spec, and snippets will unlock when the stream is complete.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            )}
            
            {/* VIEW 01: REALISTIC SPEC SHEET PAGE DOCUMENT FORM */}
            {!isGenerating && activeTab === 'DOCUMENT' && (
              <div className="space-y-10 animate-fade-in text-left">
                
                {/* 1. System Overview Info Block */}
                <div className="border border-border-match bg-surf-6 rounded-lg p-5">
                  <div className="flex gap-3">
                    <div className="text-accent-pink mt-1"><Info size={18} /></div>
                    <div>
                      <h4 className="text-sm font-bold font-geist text-text-white uppercase tracking-wider mb-2">
                        Extraction System Overview
                      </h4>
                      <p className="font-geist text-xs sm:text-sm text-[#A0A0A0] leading-relaxed">
                        {documentData.overview}
                      </p>
                    </div>
                  </div>
                </div>

                {/* 2. Color Palettes Grid */}
                <div>
                  <div className="flex items-center gap-2 mb-4 border-b border-border-match/40 pb-2">
                    <Palette size={16} className="text-accent-pink" />
                    <h3 className="text-base font-bold font-geist text-text-white uppercase tracking-wider">
                      Color Swatches & Tokens
                    </h3>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    {documentData.colors.map((color, index) => {
                      return (
                        <div 
                          key={`${color.name}-${color.hex}-${index}`}
                          onClick={() => copyColorToClipboard(color.hex)}
                          className="group bg-surf-1 border border-border-match p-3 rounded-md flex flex-col justify-between hover:border-accent-pink transition-all cursor-pointer relative"
                        >
                          {/* Color block header thumbnail preview */}
                          <div 
                            className="h-14 w-full rounded border border-border-match mb-2.5 transition-transform group-hover:scale-[1.01]"
                            style={{ backgroundColor: color.hex }}
                          />

                          <div className="space-y-1">
                            <div className="flex justify-between items-center">
                              <span className="text-xs font-mono text-[#FFFFFF]">{color.name}</span>
                              <span className="text-xs font-mono text-accent-pink">{color.hex}</span>
                            </div>
                            <p className="text-xs text-[#878787] leading-relaxed block line-clamp-2">
                              {color.useCase}
                            </p>
                          </div>

                          {/* Hover Overlay Copier hint */}
                          <div className="absolute top-2 right-2 bg-black/80 px-1.5 py-0.5 rounded text-[10px] font-mono border border-border-match text-accent-pink transition-all opacity-0 group-hover:opacity-100 flex items-center gap-1">
                            {copiedColor === color.hex ? (
                              <>
                                <Check size={8} />
                                <span>COPIED</span>
                              </>
                            ) : (
                              <>
                                <Copy size={8} />
                                <span>COPY CODES</span>
                              </>
                            )}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* 3. Typography Scales */}
                <div>
                  <div className="flex items-center gap-2 mb-4 border-b border-border-match/40 pb-2">
                    <Type size={16} className="text-accent-pink" />
                    <h3 className="text-base font-bold font-geist text-text-white uppercase tracking-wider">
                      Typography Scale Metrics
                    </h3>
                  </div>

                  <div className="overflow-x-auto rounded border border-border-match bg-surf-6">
                    <table className="w-full text-left font-mono text-xs text-text-2">
                      <thead className="bg-surf-2 text-text-white border-b border-border-match uppercase tracking-wider">
                        <tr>
                          <th className="py-2.5 px-4 font-semibold text-xs">Role Hierarchy</th>
                          <th className="py-2.5 px-4 font-semibold text-xs">Font Family</th>
                          <th className="py-2.5 px-4 font-semibold text-xs">Size px</th>
                          <th className="py-2.5 px-4 font-semibold text-xs">Weight</th>
                          <th className="py-2.5 px-4 font-semibold text-xs">Line Height</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border-match/40">
                        {documentData.typography.map((row, i) => (
                          <tr key={i} className="hover:bg-surf-2/40 transition-colors">
                            <td className="py-2.5 px-4 text-accent-pink font-semibold">{row.role}</td>
                            <td className="py-2.5 px-4">{row.font}</td>
                            <td className="py-2.5 px-4 font-bold text-text-white">{row.size}</td>
                            <td className="py-2.5 px-4">{row.weight}</td>
                            <td className="py-2.5 px-4">{row.lineHeight}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* 4. Spacing & Margin Multiples */}
                <div>
                  <div className="flex items-center gap-2 mb-4 border-b border-border-match/40 pb-2">
                    <Ruler size={16} className="text-accent-pink" />
                    <h3 className="text-base font-bold font-geist text-text-white uppercase tracking-wider">
                      Horizontal Spacing Multiples
                    </h3>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    {documentData.spacing.map((item, index) => (
                      <div key={`${item.token}-${item.px}-${index}`} className="bg-surf-1 border border-border-match p-4 rounded-md">
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-xs font-mono font-bold text-accent-pink">spacing.{item.token}</span>
                          <span className="text-xs font-bold text-text-white font-mono bg-surf-3 px-2 py-0.5 rounded border border-border-match">
                            {item.px}
                          </span>
                        </div>
                        <p className="text-[10px] text-[#A0A0A0] leading-relaxed text-left mt-1">
                          {item.context}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* 5. Component Inventory Breakdown Sheet */}
                <div>
                  <div className="flex items-center gap-2 mb-4 border-b border-border-match/40 pb-2">
                    <Box size={16} className="text-accent-pink" />
                    <h3 className="text-base font-bold font-geist text-text-white uppercase tracking-wider">
                      Component Blueprint Inventory
                    </h3>
                  </div>

                  <div className="space-y-6">
                    {documentData.components.map((comp, idx) => {
                      return (
                        <div key={`${comp.name}-${idx}`} className="bg-surf-1 border border-border-match rounded-lg p-5">
                          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                            
                            {/* Left description specs detail */}
                            <div className="lg:col-span-5 text-left space-y-3 flex flex-col justify-between">
                              <div className="space-y-2">
                                <h4 className="text-sm font-bold font-geist text-text-white uppercase tracking-wider">
                                  {comp.name}
                                </h4>
                                <p className="font-geist text-xs text-[#A0A0A0] leading-relaxed">
                                  {comp.description}
                                </p>
                              </div>

                              <div>
                                <span className="block text-xs font-mono text-text-3 uppercase tracking-wider mb-1.5 font-bold">
                                  Bound Token Dependencies:
                                </span>
                                <div className="flex flex-wrap gap-1">
                                  {comp.tokensUsed.map((tok, tokenIndex) => (
                                    <span key={`${tok}-${tokenIndex}`} className="px-2 py-0.5 bg-[#A7D7D2]/10 border border-[#A7D7D2]/25 rounded text-xs font-mono text-accent-pink">
                                      {tok}
                                    </span>
                                  ))}
                                </div>
                              </div>
                            </div>

                            {/* Center Live interactive component rendering simulator box */}
                            <div className="hidden">
                              <span className="absolute top-1.5 left-1.5 text-[9px] font-mono text-text-3 uppercase tracking-wider">
                                Live Component Playbox
                              </span>

                              {/* Simulation element selection based on compile types */}
                              {comp.name.includes('Button') ? (
                                <div className="flex flex-col gap-2 items-center">
                                  <button className="px-3.5 py-1.5 bg-[#A7D7D2] hover:bg-[#A7D7D2]/90 text-black font-semibold text-xs rounded transition-all active:scale-95 duration-100 cursor-pointer">
                                    Execute Action
                                  </button>
                                  <span className="text-xs font-mono text-[#3DD68C] mt-2">✓ Hover State Active</span>
                                </div>
                              ) : (
                                <div className="space-y-2 w-full text-left">
                                  <div className="p-2.5 bg-surf-2 border border-border-match rounded relative overflow-hidden">
                                    <div className="flex justify-between items-center text-xs font-mono text-text-3">
                                      <span>REALTIME_PING</span>
                                      <span className="text-[#3DD68C]">● 200 ms</span>
                                    </div>
                                    <div className="h-6 w-full mt-1.5 bg-bg-black rounded-sm border border-border-match/50 relative">
                                      {/* Mock sparkline path */}
                                      <div className="absolute inset-y-0 left-0 bg-accent-pink/10 w-2/3 h-full border-r border-accent-pink/40" />
                                      <span className="absolute bottom-1 right-1 text-[9px] font-mono text-text-3">active stream</span>
                                    </div>
                                  </div>
                                </div>
                              )}
                            </div>

                            {/* Right rendered component preview */}
                            <div className="lg:col-span-7 flex flex-col justify-between overflow-hidden">
                              <div className="flex justify-between items-center text-xs font-mono text-[#A0A0A0] mb-1.5">
                                <span>Preview: Rendered Component</span>
                                <span className="text-text-3">Code lives in Snippets</span>
                              </div>

                              <div className="flex-1 rounded border border-border-match bg-black p-4 min-h-[180px]">
                                {renderComponentPreview(comp, documentData)}
                              </div>
                            </div>

                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>

              </div>
            )}

            {/* VIEW 02: RAW MARKDOWN FORMAT OUTPUT */}
            {!isGenerating && activeTab === 'MARKDOWN' && (
              <div className="space-y-4 animate-fade-in text-left">
                <div className="flex justify-between items-center">
                  <span className="text-xs font-mono text-text-3">
                    Previewing generated code: <span className="text-text-white font-semibold">DESIGN.md</span>
                  </span>

                  <div className="flex flex-wrap items-center justify-end gap-2">
                    <button
                      onClick={downloadMarkdown}
                      className="flex h-8 items-center justify-center rounded border border-border-active bg-surf-2 text-text-white px-4 text-xs font-mono tracking-wide hover:border-accent-pink hover:text-accent-pink transition-all cursor-pointer"
                    >
                      <Download size={12} className="mr-1.5" />
                      <span>Download DESIGN.md</span>
                    </button>

                    <button
                      onClick={copyMarkdownToClipboard}
                      className="flex h-8 items-center justify-center rounded bg-accent-pink text-black px-4 text-xs font-mono tracking-wide hover:bg-accent-pink/90 transition-all cursor-pointer"
                    >
                      {copiedMd ? (
                        <>
                          <Check size={12} className="mr-1.5" />
                          <span>Markdown Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy size={12} className="mr-1.5" />
                          <span>Copy Entire Document</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>

                {/* Markdown text representation container */}
                <div className="rounded border border-border-match bg-black p-5 relative overflow-hidden font-mono text-xs text-text-2 max-h-[460px] overflow-y-auto leading-relaxed text-left">
                  <pre className="overflow-x-auto white-space-pre-wrap whitespace-pre-wrap">
                    {documentData.markdown}
                  </pre>
                </div>
              </div>
            )}

            {/* VIEW 03: TAILWIND JSON/CONFIG EXPORT VIEW */}
            {!isGenerating && activeTab === 'CODE_EXPORT' && (
              <div className="space-y-6 animate-fade-in text-left font-mono">
                
                {/* Micro Config Snippet 1: CSS Variables */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-xs text-[#A0A0A0]">
                    <span>CSS Variables Mapping File (:root)</span>
                    <button 
                      onClick={() => copyCodeToClipboard(cssVariableSnippet, 100)}
                      className="text-accent-pink text-[10px] hover:text-white transition-colors flex items-center gap-1"
                    >
                      {copiedCodeIdx === 100 ? <Check size={10} /> : <Copy size={10} />}
                      <span>Copy Spec</span>
                    </button>
                  </div>
                  <pre className="p-3 bg-black rounded border border-border-match text-[10px] text-text-2 text-left overflow-x-auto">
                    {cssVariableSnippet}
                  </pre>
                </div>

                {/* Micro Config Snippet 2: Tailwind Config Settings */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-xs text-[#A0A0A0]">
                    <span>Tailwind Configuration Block (tailwind.config.js / @theme)</span>
                    <button 
                      onClick={() => copyCodeToClipboard(tailwindColorSnippet, 101)}
                      className="text-accent-pink text-[10px] hover:text-white transition-colors flex items-center gap-1"
                    >
                      {copiedCodeIdx === 101 ? <Check size={10} /> : <Copy size={10} />}
                      <span>Copy Config Block</span>
                    </button>
                  </div>
                  <pre className="p-3 bg-black rounded border border-border-match text-[10px] text-text-2 text-left overflow-x-auto">
                    {tailwindColorSnippet}
                  </pre>
                </div>

                {implementationSnippets.length > 0 && (
                  <div className="space-y-4">
                    <div className="flex items-center gap-2 border-b border-border-match/40 pb-2">
                      <FileCode size={16} className="text-accent-pink" />
                      <h3 className="text-sm font-bold font-geist text-text-white uppercase tracking-wider">
                        Generated Implementation Snippets
                      </h3>
                    </div>

                    {implementationSnippets.map((component, index) => (
                      <div key={`${component.name}-${index}`} className="space-y-2">
                        <div className="flex justify-between items-center text-xs text-[#A0A0A0]">
                          <span>{component.name}</span>
                          <button
                            onClick={() => copyCodeToClipboard(component.codeSnippet, 200 + index)}
                            className="text-accent-pink text-[10px] hover:text-white transition-colors flex items-center gap-1"
                          >
                            {copiedCodeIdx === 200 + index ? <Check size={10} /> : <Copy size={10} />}
                            <span>Copy Snippet</span>
                          </button>
                        </div>
                        <pre className="p-3 bg-black rounded border border-border-match text-[10px] text-text-2 text-left overflow-x-auto whitespace-pre-wrap">
                          {component.codeSnippet}
                        </pre>
                      </div>
                    ))}
                  </div>
                )}

                {implementationSnippets.length === 0 && (
                  <div className="rounded border border-border-match bg-surf-6 p-4 text-xs text-[#A0A0A0]">
                    No component implementation code fences were generated in this DESIGN.md. The token exports above are generated from the parsed design tokens.
                  </div>
                )}

              </div>
            )}

          </div>

          {/* Prompt banner bottom info logs */}
          <div className="bg-surf-2 border-t border-border-match px-6 py-3.5 flex items-center justify-between text-xs text-text-3 font-mono">
            <span className="flex items-center gap-1 text-accent-pink">
              <Sparkles size={12} />
              <span>Perfect contrast compliance verified. All swatches AA/AAA score.</span>
            </span>
            <span>Formatted in System standard markdown style.</span>
          </div>

        </div>

      </div>
    </section>
  );
}

function renderComponentPreview(component: GeneratedDocument['components'][number], documentData: GeneratedDocument) {
  const name = getComponentSearchText(component);
  const tokens = getPreviewTokens(documentData);
  const variantLabels = component.variants.length > 0
    ? component.variants.slice(0, 4).map((variant) => variant.name)
    : ['Default', 'Active', 'Disabled'];

  if (name.includes('label') || name.includes('tag') || name.includes('pill')) {
    return (
      <div className="flex h-full min-h-[140px] items-center justify-center">
        <div className="flex flex-wrap items-center justify-center gap-3 rounded border px-5 py-4" style={{ borderColor: tokens.border, backgroundColor: tokens.surface }}>
          {variantLabels.map((label, index) => (
            <span
              key={`${label}-${index}`}
              className="inline-flex items-center rounded-full border px-3 py-1 text-xs font-semibold"
              style={{
                borderColor: index === 0 ? tokens.primary : tokens.border,
                backgroundColor: index === 0 ? `${tokens.primary}22` : tokens.surfaceAlt,
                color: index === 0 ? tokens.primary : tokens.text,
              }}
            >
              {label}
            </span>
          ))}
        </div>
      </div>
    );
  }

  if (name.includes('link')) {
    return (
      <div className="flex h-full min-h-[140px] items-center justify-center">
        <div className="flex w-full max-w-md flex-col gap-3 rounded border p-4" style={{ borderColor: tokens.border, backgroundColor: tokens.surface }}>
          {variantLabels.map((label, index) => (
            <a
              key={`${label}-${index}`}
              href="#"
              className="inline-flex items-center justify-between text-sm font-medium underline-offset-4 transition-colors hover:underline"
              style={{ color: index === 0 ? tokens.primary : tokens.text }}
            >
              <span>{label}</span>
              <ExternalLink size={13} />
            </a>
          ))}
        </div>
      </div>
    );
  }

  if (name.includes('module') || name.includes('panel') || name.includes('resource')) {
    return (
      <div className="grid h-full min-h-[140px] place-items-center">
        <div className="w-full max-w-md rounded border p-4" style={{ borderColor: tokens.border, backgroundColor: tokens.surface }}>
          <div className="flex items-center justify-between border-b pb-3" style={{ borderColor: tokens.border }}>
            <div>
              <div className="text-xs uppercase tracking-wide" style={{ color: tokens.muted }}>Module</div>
              <div className="mt-1 text-sm font-semibold" style={{ color: tokens.text }}>{component.name}</div>
            </div>
            <span className="rounded-full px-2.5 py-1 text-xs font-semibold" style={{ backgroundColor: tokens.primary, color: tokens.onPrimary }}>
              Active
            </span>
          </div>
          <div className="mt-3 grid grid-cols-3 gap-2">
            {variantLabels.slice(0, 3).map((label, index) => (
              <div key={`${label}-${index}`} className="rounded border px-2 py-2 text-center text-[11px]" style={{ borderColor: tokens.border, color: tokens.muted, backgroundColor: tokens.surfaceAlt }}>
                {label}
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (name.includes('button')) {
    return (
      <div className="flex h-full min-h-[140px] items-center justify-center gap-3">
        <button
          className="rounded-full px-5 py-2 text-sm font-semibold transition-transform active:scale-95"
          style={{ backgroundColor: tokens.primary, color: tokens.onPrimary, border: `1px solid ${tokens.border}` }}
        >
          Primary Action
        </button>
        <button className="text-sm font-medium underline-offset-4 hover:underline" style={{ color: tokens.text }}>
          Secondary Link
        </button>
      </div>
    );
  }

  if (name.includes('nav')) {
    return (
      <div className="flex h-full min-h-[140px] items-center">
        <div className="flex w-full items-center justify-between rounded border px-4 py-3" style={{ borderColor: tokens.border, backgroundColor: tokens.surface }}>
          <span className="text-sm font-semibold" style={{ color: tokens.text }}>Brand</span>
          <div className="flex gap-4 text-xs" style={{ color: tokens.muted }}>
            <span>Product</span>
            <span>Docs</span>
            <span>Pricing</span>
          </div>
          <span className="rounded-full px-3 py-1 text-xs font-semibold" style={{ backgroundColor: tokens.primary, color: tokens.onPrimary }}>
            Start
          </span>
        </div>
      </div>
    );
  }

  if (name.includes('accordion')) {
    return (
      <div className="flex h-full min-h-[140px] items-center">
        <div className="w-full overflow-hidden rounded border" style={{ borderColor: tokens.border }}>
          {['Overview', 'Details', 'Implementation'].map((label, index) => (
            <div key={label} className="flex items-center justify-between border-b px-4 py-3 text-sm last:border-b-0" style={{ borderColor: tokens.border, color: index === 0 ? tokens.text : tokens.muted }}>
              <span>{label}</span>
              <span style={{ color: tokens.primary }}>{index === 0 ? '-' : '+'}</span>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (name.includes('tab')) {
    return (
      <div className="flex h-full min-h-[140px] items-center">
        <div className="w-full">
          <div className="flex gap-2 border-b" style={{ borderColor: tokens.border }}>
            {['Overview', 'Tokens', 'Usage'].map((label, index) => (
              <span key={label} className="px-3 py-2 text-xs font-medium" style={{ color: index === 0 ? tokens.text : tokens.muted, borderBottom: index === 0 ? `2px solid ${tokens.primary}` : '2px solid transparent' }}>
                {label}
              </span>
            ))}
          </div>
          <div className="mt-4 rounded border p-3 text-xs" style={{ borderColor: tokens.border, color: tokens.muted }}>
            Active tab content area
          </div>
        </div>
      </div>
    );
  }

  if (name.includes('modal')) {
    return (
      <div className="grid h-full min-h-[140px] place-items-center">
        <div className="w-full max-w-sm rounded border p-4" style={{ borderColor: tokens.border, backgroundColor: tokens.surface }}>
          <div className="text-sm font-semibold" style={{ color: tokens.text }}>Modal Title</div>
          <p className="mt-2 text-xs" style={{ color: tokens.muted }}>Focused overlay surface using extracted color and border tokens.</p>
          <button className="mt-4 rounded-full px-4 py-2 text-xs font-semibold" style={{ backgroundColor: tokens.primary, color: tokens.onPrimary }}>
            Continue
          </button>
        </div>
      </div>
    );
  }

  if (name.includes('card')) {
    return (
      <div className="grid h-full min-h-[140px] place-items-center">
        <div className="w-full max-w-sm rounded border p-4" style={{ borderColor: tokens.border, backgroundColor: tokens.surface }}>
          <div className="text-xs uppercase tracking-wide" style={{ color: tokens.primary }}>Component Card</div>
          <div className="mt-2 text-sm font-semibold" style={{ color: tokens.text }}>Structured content block</div>
          <p className="mt-2 text-xs" style={{ color: tokens.muted }}>Previewed from extracted surface, text, border, and action tokens.</p>
        </div>
      </div>
    );
  }

  if (name.includes('badge')) {
    return (
      <div className="flex h-full min-h-[140px] items-center justify-center gap-2">
        <span className="rounded-full border px-3 py-1 text-xs font-semibold" style={{ borderColor: tokens.border, color: tokens.text }}>Default</span>
        <span className="rounded-full px-3 py-1 text-xs font-semibold" style={{ backgroundColor: tokens.primary, color: tokens.onPrimary }}>Active</span>
      </div>
    );
  }

  return (
    <div className="grid h-full min-h-[140px] place-items-center">
      <div className="w-full max-w-md overflow-hidden rounded border" style={{ borderColor: tokens.border, backgroundColor: tokens.surface }}>
        <div className="flex items-center justify-between border-b px-4 py-3" style={{ borderColor: tokens.border }}>
          <div className="text-sm font-semibold" style={{ color: tokens.text }}>{component.name}</div>
          <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: tokens.primary }} />
        </div>
        <div className="space-y-3 p-4">
          <div className="h-2 w-3/4 rounded-full" style={{ backgroundColor: tokens.border }} />
          <div className="h-2 w-1/2 rounded-full" style={{ backgroundColor: tokens.border }} />
          <div className="flex flex-wrap gap-2 pt-1">
            {variantLabels.slice(0, 3).map((label, index) => (
              <span key={`${label}-${index}`} className="rounded-full border px-2.5 py-1 text-[11px]" style={{ borderColor: tokens.border, color: tokens.muted }}>
                {label}
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

function getComponentSearchText(component: GeneratedDocument['components'][number]): string {
  return [
    component.name,
    component.description,
    ...component.variants.flatMap((variant) => [variant.name, variant.details]),
    ...component.tokensUsed,
  ].join(' ').toLowerCase();
}

function getPreviewTokens(documentData: GeneratedDocument) {
  const background = pickDocumentColor(documentData, ['background', 'surface', 'canvas'], '#000000');
  const surfaceAlt = pickDocumentColor(documentData, ['surface2', 'card', 'panel'], '#111111');
  const text = pickDocumentColor(documentData, ['text', 'foreground'], '#F4F4F4');
  const muted = pickDocumentColor(documentData, ['text2', 'muted', 'secondary'], '#A0A0A0');
  const border = pickDocumentColor(documentData, ['border', 'stroke', 'divider'], '#252525');
  const primary = pickDocumentColor(documentData, ['primary', 'accent', 'brand'], '#A7D7D2');

  return {
    surface: background,
    surfaceAlt,
    text,
    muted,
    border,
    primary,
    onPrimary: getReadableTextColor(primary),
  };
}

function pickDocumentColor(documentData: GeneratedDocument, names: string[], fallback: string): string {
  const color = documentData.colors.find((item) => {
    const searchable = `${item.name} ${item.useCase}`.toLowerCase();
    return names.some((name) => searchable.includes(name));
  });

  return color?.hex ?? fallback;
}

function getReadableTextColor(hex: string): string {
  const normalized = hex.replace('#', '');
  if (normalized.length !== 6) return '#000000';

  const red = parseInt(normalized.slice(0, 2), 16);
  const green = parseInt(normalized.slice(2, 4), 16);
  const blue = parseInt(normalized.slice(4, 6), 16);
  const luminance = (0.299 * red + 0.587 * green + 0.114 * blue) / 255;

  return luminance > 0.58 ? '#000000' : '#FFFFFF';
}

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'token';
}

function buildComponentBlueprint(component: GeneratedDocument['components'][number]): string {
  const variants = component.variants.length > 0
    ? component.variants.map((variant) => `  - ${variant.name}: ${variant.details}`).join('\n')
    : '  - default: extracted from source analysis';
  const tokens = component.tokensUsed.length > 0 ? component.tokensUsed.join(', ') : 'none listed';

  return `component: ${component.name}\ndescription: ${component.description}\nvariants:\n${variants}\ntokensUsed: ${tokens}`;
}
